name: run-tests
on: [push, pull_request]

jobs:
  build-and-test:
    runs-on: 
      group: k23a

    steps:
      - uses: actions/checkout@v4


      - name: Configure project
        run: |
          cmake -S . -B build

      - name: Build only selected test targets
        run: |
          cmake --build build --target test_hopscotch test_robinhood test_cuckoo test_column_store test_unchained -j$(nproc)


      - name: Run Hopscotch tests
        run: |
          cd build && ./test_hopscotch

      - name: Run RobinHood tests
        run: |
          cd build && ./test_robinhood

      - name: Run Cuckoo tests
        run: |
          cd build && ./test_cuckoo

      - name: Run columnar and materialize tests
        run: |
          cd build && ./test_column_store

      - name: Run unchained tests
        run: |
          cd build && ./test_unchained

name: Workflow for leaderboard submission

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  leaderboard:
    name: leaderboard
    runs-on:
      group: benchmark
    steps:
      - name: Checkout code
        uses: actions/checkout@v5

      - name: Configure CMake
        run: |
          cmake -S . -B build -DCMAKE_BUILD_TYPE=Release -Wno-dev

      - name: Build project
        run: |
          cmake --build build --target fast_unc -- -j 6 leaderboard
          
      - name: Run for leaderboard
        run: |
          leaderboard.sh